### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by guerreiropedr0** [tresorsawasawa/Movie-App#3]
Banlon Jones:
- In lines 22 to 27, on the JS file, you did a wonderful job displaying the movies!
- I didn't find any issue, so great job :smile:

Dejan Vujovic:
- No issues found! Beautiful job! 

Pedro Guerreiro:
- I like how you declared every constant in the beginning, it looks organized.
I think from what we learned in the previous lessons, you could use arrow functions 
instead of the traditional way to declare functions.
- I see that in line 43 you have a comment, I don't think that it is necessary.
Clean code is self-explanatory, and your code is very clean. Kindly remove the 
comment.
- In line 48 you are console logging the responseData. Console logging should
always be removed after every push. I think it would look better if you removed
it.

**Comment by tresorsawasawa** [comment]
I really appreciate your reviews.
